### ISSUE TITLE
更新数据库失败 

### ISSUE THREAD

**Issue by crazyxhz** [jkzhang2019/cldup#1]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/6551888/235389993-2663a7ed-852c-4aea-98ce-c6e9dc570756.png">
DSM 7.1.1-42962 Update 5 支持吗？

**Comment by jkzhang2019** [comment]
支持的。
1.  执行 cldup -u 消耗的时间长吗？（几秒钟，还是几分钟或者更久？典型速度视目录内的文件大小而定，差不多50MB/s的量级吧。）
2. 修改过配置项吗？ 如果编辑过，编辑成了什么样子？
3. 存储卷的名称是不是/volume1   ？

**Comment by crazyxhz** [comment]
> 支持的。
> 
> 1. 执行 cldup -u 消耗的时间长吗？（几秒钟，还是几分钟或者更久？典型速度视目录内的文件大小而定，差不多50MB/s的量级吧。）
> 2. 修改过配置项吗？ 如果编辑过，编辑成了什么样子？
> 3. 存储卷的名称是不是/volume1   ？

1. 秒退出
2. 就改了 BASEDIRS='/volume1 /volume3 /volume4'   其他默认
3. 默认是 /volume1

**Comment by jkzhang2019** [comment]
多目录支持有点问题。
更新代码，同时修改BASEDIRS为以下形式：
BASEDIRS=('/volume1'  '/volume3'  '/volume4')

**Comment by jkzhang2019** [comment]
fixed, manual updated

**Comment by crazyxhz** [comment]
已经跑了两天了🤣 有问题吗？ tail -f allfiles.db.new.byscan.2824 倒是一直有输出

**Comment by jkzhang2019** [comment]
如果文件容量很大而且cpu不太行，算正常，还好库是增量维护，计算量不浪费。
wc -l 下几个中间文件，能预估目前的完成率——每行代表一个文件，数这个byscan文件的行数就大致知道完成率了。

**Comment by jkzhang2019** [comment]
后来跑完了吗？
改进了下，能显著提升建库的速度。

**Comment by crazyxhz** [comment]
> 后来跑完了吗？ 改进了下，能显著提升建库的速度。

跑了5天跑了70%😅，这会儿中断，换成新的代码，数据库兼容吗？

**Comment by jkzhang2019** [comment]
不兼容，在建库的时候，原来是计算文件的全文摘要，现在改成了只计算头部4K。

**Comment by jkzhang2019** [comment]
您的设备是什么配置，多少T的数据，主要内容是小文件换是大文件（视频、电影等）？

**Comment by crazyxhz** [comment]
> 您的设备是什么配置，多少T的数据，主要内容是小文件换是大文件（视频、电影等）？

<img width="755"  alt="image" src="https://github.com/jkzhang2019/cldup/assets/6551888/b7c0d254-d01c-423b-a1be-31e09ae4395a">

大概18T数据，3个盘，大文件小文件都有，电影，代码
建议加个黑名单？ node_modules, .git 之类的可以过滤下

**Comment by jkzhang2019** [comment]
旧版18T数据跑这么久还算正常。

**Comment by jkzhang2019** [comment]
尽快更新下新版吧，发现一个比较严重的问题，会误判重复文件。
